---
# tasks file for ansible-role-set-cloud9
- name: Download pulumi installer
  get_url:
    url: https://get.pulumi.com
    dest: /tmp/get-pulumi.sh
    mode: '0755'

- name: install pulumi
  script: "/tmp/get-pulumi.sh"
  register: result
  changed_when: no
  become: no
