---
# tasks file for ansible-role-set-cloud9
- name: clone repo
  git: 
    repo: https://github.com/awslabs/git-secrets.git
    dest: /tmp/git-secrets
    update: yes
    force: yes

- name: make
  shell: "sudo make install"
  register: result
  changed_when: no
  args:
    chdir: /tmp/git-secrets/

- name: install git secret
  shell: "git secrets --install --force"
  register: result
  changed_when: no
  args:
    chdir: /home/ec2-user/environment/aws-cloud9-codecommit

- name: regsiter aws
  shell: "git secrets --register-aws --global"
  register: result
  changed_when: no
  args:
    chdir: /home/ec2-user/environment/aws-cloud9-codecommit
