---
# tasks file for ansible-role-set-cloud9
- name: install ecs-cli
  shell: "sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest"
  register: result
  changed_when: no

- name: chmod
  shell: "sudo chmod +x /usr/local/bin/ecs-cli"
  register: result
  changed_when: no
