---
- hosts: all
  connection: local
  become: yes

  roles:
    - role: william-yeh.fluentd

  vars:
    tdagent_plugins:
      - fluent-plugin-multiprocess
      - fluent-plugin-flowcounter
      - fluent-plugin-elasticsearch

  # tasks:
  #   - include_tasks: tasks/main.yml
